backend:
  name: git-gateway
  branch: main
media_folder: assets/img
collections:
  - label: Base Information
    name: base information
    files:
      - label: Address
        name: Address
        file: content/markdown/address.md
        fields:
          - label: Street
            name: street
            widget: string

          - label: City
            name: city
            widget: string

          - label: State
            name: state
            widget: string

      - label: Open Hours
        name: open hours
        file: content/markdown/openHours.md
        fields:
          - label: Text
            name: text
            widget: string

      - label: Contacts
        name: contacts
        file: content/markdown/contacts.md
        fields:
          - label: Phone Number
            name: phone number
            widget: string

          - label: Email Address
            name: email address
            widget: string

      - label: Social Media
        name: social media
        file: content/markdown/socialMedia.md
        fields:
          - label: Facebook
            name: facebook
            widget: string

          - label: Instagram
            name: instagram
            widget: string

  - label: Pretzels
    name: pretzels
    folder: content/markdown/pretzel
    create: true
    identifier_field: name
    slug: "{{slug}}"
    label_singular: Pretzel
    fields:
        - label: Display on the website?
          name: display
          widget: boolean
          default: true

        - label: Name
          name: name
          widget: string

        - label: Description
          name: description
          widget: text
          required: false
          
        - label: Image
          name: image
          widget: image
          required: false
          
        - label: Prices
          name: prices
          widget: list
          label_singular: price
          min: 1
          fields:
            - label: Price
              name: price
              widget: number
              value_type: float
                  
            - label: Size
              name: size
              widget: string
              required: false
  
  - label: Ice Cream
    name: ice cream
    folder: content/markdown/iceCream
    create: true
    identifier_field: name
    slug: "{{slug}}"
    label_singular: Ice Cream
    fields:
        - label: Display on the website?
          name: display
          widget: boolean
          default: true

        - label: Name
          name: name
          widget: string

        - label: Description
          name: description
          widget: text
          required: false
          
        - label: Image
          name: image
          widget: image
          required: false
          
        - label: Prices
          name: prices
          widget: list
          label_singular: price
          min: 1
          fields:
            - label: Price
              name: price
              widget: number
              value_type: float
                  
            - label: Size
              name: size
              widget: string
              required: false

  - label: Water Ice
    name: water ice
    folder: content/markdown/waterIce
    create: true
    identifier_field: name
    slug: "{{slug}}"
    label_singular: Water Ice
    fields:
        - label: Display on the website?
          name: display
          widget: boolean
          default: true

        - label: Name
          name: name
          widget: string

        - label: Description
          name: description
          widget: text
          required: false
          
        - label: Image
          name: image
          widget: image
          required: false
          
        - label: Prices
          name: prices
          widget: list
          label_singular: price
          min: 1
          fields:
            - label: Price
              name: price
              widget: number
              value_type: float
                  
            - label: Size
              name: size
              widget: string
              required: false

  - label: Dips
    name: dips
    folder: content/markdown/dip
    create: true
    identifier_field: name
    slug: "{{slug}}"
    label_singular: Dip
    fields:
        - label: Display on the website?
          name: display
          widget: boolean
          default: true

        - label: Name
          name: name
          widget: string

        - label: Description
          name: description
          widget: text
          required: false

        - label: Image
          name: image
          widget: image
          required: false
          
        - label: Prices
          name: prices
          widget: list
          label_singular: price
          min: 1
          fields:
            - label: Price
              name: price
              widget: number
              value_type: float
                  
            - label: Size
              name: size
              widget: string
              required: false

  - label: Drinks
    name: drinks
    folder: content/markdown/drink
    create: true
    identifier_field: name
    slug: "{{slug}}"
    label_singular: Drink
    fields:
        - label: Display on the website?
          name: display
          widget: boolean
          default: true

        - label: Name
          name: name
          widget: string

        - label: Description
          name: description
          widget: text
          required: false
          
        - label: Image
          name: image
          widget: image
          required: false
          
        - label: Prices
          name: prices
          widget: list
          label_singular: price
          min: 1
          fields:
            - label: Price
              name: price
              widget: number
              value_type: float
                  
            - label: Size
              name: size
              widget: string
              required: false