backend:
  name: git-gateway
  branch: main
media_folder: assets/img
collections:
  - label: 'Pretzels'
    name: 'pretzels'
    folder: 'content/markdown/pretzels'
    create: true
    identifier_field: name
    slug: '{{slug}}'
    fields:
      - { label: 'Name', name: 'name', widget: 'string', required: true }
      - { label: 'Type', name: 'type', widget: 'list', allow_add: false, default: ["news"] }
      - { label: 'Image', name: 'image', widget: 'image' }
      - { label: 'Prices', name: 'prices', widget: 'list', field: { label: 'Amount', name: 'ammount', widget: 'number', value_type: 'float' }, { label: 'Name', name: 'name', widget: 'string', required: true } }