backend:
  name: git-gateway
  branch: main
media_folder: assets/img
collections:
  - label: Pretzels
    name: pretzels
    folder: content/markdown/pretzel
    create: true
    identifier_field: name
    slug: "{{slug}}"
    label_singular: Pretzel
    fields:
        - label: Name
          name: name
          widget: string

        - label: Description
          name: description
          widget: string
          required: false
          
        - label: Image
          name: image
          widget: image
          required: false
          
        - label: Prices
          name: prices
          widget: list
          label_singular: price
          min: 1
          field:
            label: Price
            name: price
            widget: object
            fields:
                - label: Ammount
                  name: ammount
                  widget: number
                  value_type: float
                  
                - label: Size
                  name: size
                  widget: string
                  required: false
  
  - label: Pretzel Dogs
    name: pretzel dogs
    folder: content/markdown/pretzelDog
    create: true
    identifier_field: name
    slug: "{{slug}}"
    label_singular: Pretzel Dog
    fields:
        - label: Name
          name: name
          widget: string

        - label: Description
          name: description
          widget: string
          required: false
          
        - label: Image
          name: image
          widget: image
          required: false
          
        - label: Prices
          name: prices
          widget: list
          label_singular: price
          min: 1
          field:
            label: Price
            name: price
            widget: object
            fields:
                - label: Ammount
                  name: ammount
                  widget: number
                  value_type: float
                  
                - label: Size
                  name: size
                  widget: string
                  required: false

  - label: Ice Cream
    name: ice cream
    folder: content/markdown/iceCream
    create: true
    identifier_field: name
    slug: "{{slug}}"
    label_singular: Ice Cream
    fields:
        - label: Name
          name: name
          widget: string

        - label: Description
          name: description
          widget: string
          required: false
          
        - label: Image
          name: image
          widget: image
          required: false
          
        - label: Prices
          name: prices
          widget: list
          label_singular: price
          min: 1
          field:
            label: Price
            name: price
            widget: object
            fields:
                - label: Ammount
                  name: ammount
                  widget: number
                  value_type: float
                  
                - label: Size
                  name: size
                  widget: string
                  required: false

  - label: Water Ice
    name: water ice
    folder: content/markdown/waterIce
    create: true
    identifier_field: name
    slug: "{{slug}}"
    label_singular: Water Ice
    fields:
        - label: Name
          name: name
          widget: string

        - label: Description
          name: description
          widget: string
          required: false
          
        - label: Image
          name: image
          widget: image
          required: false
          
        - label: Prices
          name: prices
          widget: list
          label_singular: price
          min: 1
          field:
            label: Price
            name: price
            widget: object
            fields:
                - label: Ammount
                  name: ammount
                  widget: number
                  value_type: float
                  
                - label: Size
                  name: size
                  widget: string
                  required: false

  - label: Dips
    name: dips
    folder: content/markdown/dip
    create: true
    identifier_field: name
    slug: "{{slug}}"
    label_singular: Dip
    fields:
        - label: Name
          name: name
          widget: string

        - label: Description
          name: description
          widget: string
          required: false

        - label: Image
          name: image
          widget: image
          required: false
          
        - label: Prices
          name: prices
          widget: list
          label_singular: price
          min: 1
          field:
            label: Price
            name: price
            widget: object
            fields:
                - label: Ammount
                  name: ammount
                  widget: number
                  value_type: float
                  
                - label: Size
                  name: size
                  widget: string
                  required: false