backend:
  name: git-gateway
  branch: main
media_folder: assets/img
collections:
  - label: 'Pretzels'
    name: 'pretzels'
    folder: 'content/markdown/pretzels'
    create: true
    identifier_field: 'name'
    slug: '{{slug}}'
    label_singular: 'Add Pretzel'
    fields:
      - { label: 'Name', name: 'name', widget: 'string', required: true }
      - { label: 'Image', name: 'image', widget: 'image' }
  
  - label: 'Pretzel Dogs'
    name: 'pretzel dogs'
    folder: 'content/markdown/pretzeldogs'
    create: true
    identifier_field: 'name'
    slug: '{{slug}}'
    label_singular: 'Add Pretzel Dog'
    fields:
      - { label: 'Name', name: 'name', widget: 'string', required: true }
      - { label: 'Image', name: 'image', widget: 'image' }

  - label: 'Ice Cream'
    name: 'ice cream'
    folder: 'content/markdown/icecream'
    create: true
    identifier_field: 'name'
    slug: '{{slug}}'
    label_singular: 'Add Ice Cream'
    fields:
      - { label: 'Name', name: 'name', widget: 'string', required: true }
      - { label: 'Image', name: 'image', widget: 'image' }

  - label: 'Water Ice'
    name: 'water ice'
    folder: 'content/markdown/waterice'
    create: true
    identifier_field: 'name'
    slug: '{{slug}}'
    label_singular: 'Add Water Ice'
    fields:
      - { label: 'Name', name: 'name', widget: 'string', required: true }
      - { label: 'Image', name: 'image', widget: 'image' }

  - label: 'Dips'
    name: 'dips'
    folder: 'content/markdown/dips'
    create: true
    identifier_field: 'name'
    slug: '{{slug}}'
    label_singular: 'Add Dip'
    fields:
      - { label: 'Name', name: 'name', widget: 'string', required: true }
      - { label: 'Image', name: 'image', widget: 'image' }